### PR TITLE
system on windows

### PR DESCRIPTION
**Pull request by mattn**
but still fail on owrite.zy because i don't have diff at /usr/bin/diff

### CODE REVIEW

**Comment by glycerine** [comment]
Thank you @mattn 
I made the owrite.zy check conditional on not being on windows.

**Comment by mattn** [comment]
thanks. if you provide check OS like ` (cond ((eq zygo-os 'windows)`, it's usefull maybe.

**Comment by glycerine** [comment]
yes, I just did. You will get it if you pull master. The diff is here:
https://github.com/glycerine/zygomys/commit/bb15843ab5c888157916bef9c195e8d12317cb80

**Comment by mattn** [comment]
:+1:

**Pull request merged**
